name: Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        HOST: ${{secrets.HOST}}
        USERNAME: ${{secrets.USERNAME}}
        PORT: ${{secrets.PORT}}
        PASSWORD: ${{ secrets.PASSWORD }}
        source: "."
        target: "/home/ubuntu/sites/lochedeoro"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{secrets.HOST}}
        USERNAME: ${{secrets.USERNAME}}
        PORT: ${{secrets.PORT}}
        PASSWORD: ${{secrets.PASSWORD}}
        script: runuser -l ubuntu -c 'bash /home/ubuntu/loche.sh'
